### ISSUE TITLE
Ability to revert text formatting

### ISSUE THREAD

**Issue by emvaized** [davidkonrad/toUnicodeVariant#1]
Thanks for your code, this is exactly what I was looking for!

I have a small question, however. 
I want to display some button which will turn the selected text to bold/italic, and revert the formatting when clicked the second time.

Is it possible to achieve somehow? Maybe `toUnicodeVariant` function could check the resulting string, and if it's 100% equal to the passed one it could apply some "normal" variant parsing?

**Comment by emvaized** [comment]
Would be also nice addition to try combining newly added style with previously added.
For example, if string was previosuly `bold`-formatted, trying to format it in `italic` should result in `bold italic `style applied

**Comment by davidkonrad** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize
