### ISSUE TITLE
conversion of multilingual letters

### ISSUE THREAD

**Issue by ainkalda** [davidkonrad/toUnicodeVariant#4]
Hi,

Very good and useful code, but is there any possibility to convert multilingual letters like **ä**, **ü**, **č**, **õ**, etc.?
At least to bold or italic?
Does Unicode have support for these symbols?

Thank You

**Comment by davidkonrad** [comment]
Good question. I was excatly in the process of looking for some more "specials", I will look after these ä, ü, č, õ and similar as well (letters with diacritics). It is very possible they are just located on another "address" because they were added later on.

**Comment by davidkonrad** [comment]
I gaurantee, there is no way those characters will be supported "natively", ever. I have loooked and looked, hoped there were some addendums.

However, there are a lot of diacriticals to work with -> http://www.unicode.org/charts//PDF/Unicode-4.0/U40-0300.pdf

So I try to mimick those characters. Se README.md. It looks OK for some variants, really awful for others. 

I think it is the best we can do: Catch the special char, fallback to latin and *"style" it with diacritics. At least better than nothing. 

If you have more characters that nee such kind of "support", raise an issue.
